### ISSUE TITLE
[Feature Request] Support for PGS/SUP (S_HDMV/PGS)

### ISSUE THREAD

**Issue by ghost** [mathiasvr/mkv-subtitle-extractor#3]
I know this repo is getting a bit old, but I was wondering if adding support for extracting SUP/PGS files from MKV would be possible?

**Comment by mathiasvr** [comment]
Whoops, if you have a sample file I can try to take a look at it

**Comment by ghost** [comment]
I'll see what I can do..

**Comment by ghost** [comment]
Sorry, I wasn't able to find any legal mkvs with PGS in it. I'll just close the issue for now.
